=head1 NAME

Ipsefact - Global IP-Address Inspector as Web Application 

=head1 SYNOPSIS

  $ plackup

=head1 DESCRIPTION

Ipsefact is web application based Nephia.

=head1 AUTHOR

ytnobody

=head1 SEE ALSO

L<http://ipsefact.ytnobody.net/>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

